### PR TITLE
add chorusone vesting account

### PR DESCRIPTION
**Pull request by joe-bowman**
add missing chorusone vesting account

### CODE REVIEW

**Comment by zmanian** [comment]
you need to increment the amount of `stake` in your account by 500000 and update `unbonded_tokens` as well.

**Comment by joe-bowman** [comment]
yeah, missed that - thanks

**Comment by joe-bowman** [comment]
what is `delegated_free` - it seems to vary...

**Comment by zmanian** [comment]
You can see how delegated_free is calculated here
https://github.com/cosmos/game-of-stakes/blob/master/genesisify/add-vesting.py

**Comment by joe-bowman** [comment]
@zmanian - updated the delegated free amount as requested.

**Pull request closed without merging**
