### PR TITLE
add zednode gentx

### PR DESCRIPTION
**Pull request by rloomba**
had to add my addr to genesis.json

```json
{
                "address": "cosmos1jjsmtd75xyn9fyaexgpkaem6ulj5kv5ddl5a02",
                "coins": [
                    {
                        "denom": "STAKE",
                        "amount": "10000"
                    },
                    {
                        "denom": "photinos",
                        "amount": "10000000000"
                    }
                ],
                "sequence_number": "0",
                "account_number": "0"
            }
```

Thanks @zmanian for all your hard work on this!

### CODE REVIEW

**Comment by zmanian** [comment]
I can't find any record of you in our registration process.

**Comment by zmanian** [comment]
The address I have in my records for you is "cosmos1anrnemrx8tcy6f5zy2ukleweyg8m3v823qg87d"

**Comment by zmanian** [comment]
What's up with the new address?

**Comment by rloomba** [comment]
Ah we just generated a new address, think there was some confusion before so figured I’d just make a fresh one.

Let me know if that’s an issue.

**Comment by zmanian** [comment]
you can't use the existing the existing address? Just more cause I need to also delete your old address the accounts

**Comment by rloomba** [comment]
@zmanian just updated using the original `cosmos1anrnemrx8tcy6f5zy2ukleweyg8m3v823qg87d` address. Sorry for the confusion. Should be good to merge now.

**Pull request merged**
